language: node_js
node_js:
- "0.10"

notifications:
  webhooks:
    urls:
      - https://qa1.kore.com/hooks/7b349a4d1e2f8335fa32d3bb74f79ce6
    on_success: [always|never|change] # default: always
    on_failure: [always|never|change] # default: always
    on_start: [always|never|change] # default: always
